package modelo;
// Generated 05-mar-2017 12:19:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Buceadores generated by hbm2java
 */
public class Buceadores  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String titulacion;
     public Set inmersions = new HashSet(0);

    public Buceadores() {
    }

	
    public Buceadores(String nombre, String titulacion) {
        this.nombre = nombre;
        this.titulacion = titulacion;
    }
    public Buceadores(String nombre, String titulacion, Set inmersions) {
       this.nombre = nombre;
       this.titulacion = titulacion;
       this.inmersions = inmersions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTitulacion() {
        return this.titulacion;
    }
    
    public void setTitulacion(String titulacion) {
        this.titulacion = titulacion;
    }
    public Set getInmersions() {
        return this.inmersions;
    }
    
    public void setInmersions(Set inmersions) {
        this.inmersions = inmersions;
    }




}


