package modelo;
// Generated 05-mar-2017 12:19:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Inmersion generated by hbm2java
 */
public class Inmersion  implements java.io.Serializable {


     private Integer id;
     private int idMonitor;
     private String lugar;
     private String duracion;
     public Set buceadoreses = new HashSet(0);

    public Inmersion() {
    }

	
    public Inmersion(int idMonitor, String lugar, String duracion) {
        this.idMonitor = idMonitor;
        this.lugar = lugar;
        this.duracion = duracion;
    }
    public Inmersion(int idMonitor, String lugar, String duracion, Set buceadoreses) {
       this.idMonitor = idMonitor;
       this.lugar = lugar;
       this.duracion = duracion;
       this.buceadoreses = buceadoreses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdMonitor() {
        return this.idMonitor;
    }
    
    public void setIdMonitor(int idMonitor) {
        this.idMonitor = idMonitor;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }
    public Set getBuceadoreses() {
        return this.buceadoreses;
    }
    
    public void setBuceadoreses(Set buceadoreses) {
        this.buceadoreses = buceadoreses;
    }




}


