package modelo;
// Generated 05-mar-2017 12:19:22 by Hibernate Tools 4.3.1



/**
 * Monitor generated by hbm2java
 */
public class Monitor  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String club;
     private String provincia;

    public Monitor() {
    }

    public Monitor(String nombre, String club, String provincia) {
       this.nombre = nombre;
       this.club = club;
       this.provincia = provincia;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getClub() {
        return this.club;
    }
    
    public void setClub(String club) {
        this.club = club;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }




}


